# Generated by Django 5.0.2 on 2024-04-10 10:14

import django.contrib.auth.models
import django.db.models.deletion
import src.apps.common.utills
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.group')),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='', validators=[src.apps.common.utills.image_validate])),
                ('admin_id', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('web', 'Web'), ('network', 'Network'), ('cyber', 'Cyber'), ('cloud', 'Cloud'), ('art', 'Art'), ('food', 'Food'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('lifestyle', 'Lifestyle'), ('sports', 'Sports'), ('travel', 'Travel'), ('other', 'Other')], default='web', max_length=100)),
                ('total_members', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
