# Generated by Django 5.0.4 on 2024-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementgroup',
            name='invite_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcementgroup',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
