# Generated by Django 5.0.2 on 2024-04-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementgroup',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
