# Generated by Django 5.0.4 on 2024-06-02 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMemberShip',
            new_name='GroupMember',
        ),
        migrations.RemoveField(
            model_name='announcementgroup',
            name='members',
        ),
    ]
