# Generated by Django 5.0.4 on 2024-06-02 09:19

import django.db.models.deletion
import src.apps.common.utills
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_rename_groupmembership_groupmember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementgroup',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='announcementgroup',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcementgroup',
            name='image',
            field=models.ImageField(default='', upload_to='groups/', validators=[src.apps.common.utills.image_validate]),
        ),
    ]
