# Generated by Django 5.0.4 on 2024-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_announcementgroup_group_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementgroup',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcementgroup',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
