# Generated by Django 5.0.4 on 2024-06-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_announcementgroup_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementgroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='active', max_length=20),
        ),
    ]
