# Generated by Django 5.0.4 on 2024-06-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='admin',
            new_name='user',
        ),
    ]
