# Generated by Django 5.0.4 on 2024-12-06 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('group_join', 'Group Join'), ('group_leave', 'Group Leave'), ('announcement_create', 'Announcement Create'), ('announcement_update', 'Announcement Update'), ('announcement_comment_create', 'Announcement Comment Create'), ('announcement_like', 'Announcement Like'), ('announcement_unlike', 'Announcement Unlike')], default='group_join', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0762c2a5-64ae-4a8e-9857-f69be1b8e3f0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
