# Generated by Django 5.0.4 on 2024-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
