# Generated by Django 5.0.4 on 2024-07-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('event', 'Event'), ('news', 'News'), ('update', 'Update'), ('offer', 'Offer'), ('product launch', 'Product Launch'), ('training', 'Training'), ('bootcamp', 'Bootcamp')], default='event', max_length=100),
        ),
    ]
