# Generated by Django 5.0.4 on 2024-12-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_dislike_announcement_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='like',
        ),
    ]
