# Generated by Django 5.0.2 on 2024-04-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcementcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='paid_for_email',
            field=models.BooleanField(default=False),
        ),
    ]
