# Generated by Django 5.0.4 on 2024-04-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='payment_method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('e-sewa', 'E-SEWA'), ('paypal', 'Paypal')], default='khalti', max_length=100),
        ),
    ]
