# Generated by Django 5.0.2 on 2024-04-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_alter_announcement_paid_for_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
