# Generated by Django 5.0.2 on 2024-04-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_announcement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
    ]
