# Generated by Django 5.0.4 on 2024-04-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_alter_announcement_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pidx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
