# Generated by Django 5.0.4 on 2024-05-16 06:36

import src.apps.common.utills
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_announcement_pidx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(upload_to='announcement', validators=[src.apps.common.utills.image_validate]),
        ),
    ]
