# Generated by Django 5.0.4 on 2024-05-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('khalti', 'Khalti'), ('e-sewa', 'E-SEWA'), ('paypal', 'Paypal')], default='khalti', max_length=100, null=True),
        ),
    ]
