# Generated by Django 5.0.4 on 2024-06-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_announcementcomment_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='admin',
            new_name='user',
        ),
    ]
