# Generated by Django 5.0.4 on 2024-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0010_rename_admin_announcement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='pidx',
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=100),
        ),
        migrations.AddField(
            model_name='announcement',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
