# Generated by Django 5.0.4 on 2024-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0011_remove_announcement_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
